---
title: "8_Focal Figures and Maps"
author: "Leslie Jones"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(rgdal)
library(lubridate)
library(gridExtra)
library(arsenal)
library(knitr)
library(magick)
library(gganimate)
library(transformr)
library(spdplyr)
library(sp)
library(dplyr)
library(ggplot2)
library(ggmap)
library(rgeos)
library(readr)
library(tibble)
library(arcgisbinding)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
#Load predictions data frame.
load(file = "output/preds.Rdata")

#load chinook rearing and spawning datasets
load(file = "output/K_r.Rdata")
load(file = "output/K_s.Rdata")
load(file = "output/K_p.Rdata")

load(file = "output/CO_r.Rdata")
load(file = "output/CO_s.Rdata")
load(file = "output/CO_p.Rdata")


```

```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
#mean annual temperatures for all chinook habitat - plot trends in temperatures and variation among rcas
interannual <- K_p %>% group_by(year) %>% mutate(yr_mn=mean(preds), yr_sd=sd(preds)) 

ggplot(data=interannual) +
  geom_line(aes(x = year, y = yr_mn))  + geom_smooth(aes(x = year, y = yr_mn),method = "lm") +
  labs(x="Year", y="Stream Temperature")+
  ggtitle("Mean annual stream temperatures for Chinook habitat") 

ggsave("salmon_figs/Mean annual stream temperatures for Chinook habitat.jpeg", plot=last_plot())

ggplot(data=interannual) +
  geom_line(aes(x = year, y = yr_sd)) + geom_smooth(aes(x = year, y = yr_sd),method = "lm") +
  labs(x="Year", y="Standard Deviation of Stream Temperatures")+
  ggtitle("Variability of mean annual temperatures among RCAs for Chinook habiat") 

ggsave("salmon_figs/Variability of mean annual temperatures among RCAs for Chinook habiat.jpeg", plot=last_plot())

#same for Coho
interannual_CO <- CO_p %>% group_by(year) %>% mutate(yr_mn=mean(preds), yr_sd=sd(preds)) 

ggplot(data=interannual_CO) +
  geom_line(aes(x = year, y = yr_mn))  + geom_smooth(aes(x = year, y = yr_mn),method = "lm") +
  labs(x="Year", y="Stream Temperature")+
  ggtitle("Mean annual stream temperatures for Coho habitat") 

ggsave("salmon_figs/Mean annual stream temperatures for Coho habitat.jpeg", plot=last_plot())

ggplot(data=interannual_CO) +
  geom_line(aes(x = year, y = yr_sd)) + geom_smooth(aes(x = year, y = yr_sd),method = "lm") +
  labs(x="Year", y="Standard Deviation of Stream Temperatures")+
  ggtitle("Variability of mean annual temperatures among RCAs for Coho habitat") 

ggsave("salmon_figs/Variability of mean annual temperatures among RCAs for Coho habiat.jpeg", plot=last_plot())


```

```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
#Mean daily temps for each year - faceted by decade - and plotted by life-stage for Chinook

#Chinook rearing
decade_K_r <- K_r %>% group_by(day, year) %>% 
  summarize(mean_yr = mean(preds), sd_yr = sd(preds)) %>% mutate(decade=case_when(year< 1990 ~ 1980, year >= 1990 & year < 2000 ~ 1990, year >=2000 & year < 2010 ~ 2000, year>2009 ~ 2010))

ggplot(data=decade_K_r) +
  geom_smooth(aes(x = day, y = mean_yr, color = as.factor(year)), show.legend = FALSE) + facet_wrap(~decade) + 
  ggtitle("Mean daily temperatures by year for Chinook rearing habitat") 

ggsave("salmon_figs/Mean daily chinook rearing thermal curve.jpeg", plot=last_plot())

#Chinook spawning
decade_K_s <- K_s %>% group_by(day, year) %>% 
  summarize(mean_yr = mean(preds), sd_yr = sd(preds)) %>% mutate(decade=case_when(year< 1990 ~ 1980, year >= 1990 & year < 2000 ~ 1990, year >=2000 & year < 2010 ~ 2000, year>2009 ~ 2010))

ggplot(data=decade_K_s) +
  geom_smooth(aes(x = day, y = mean_yr, color = as.factor(year)), show.legend = FALSE) + facet_wrap(~decade) + 
  ggtitle("Mean daily temperatures by year for Chinook spawning habitat") 

ggsave("salmon_figs/Mean daily chinook spawning thermal curve.jpeg", plot=last_plot())

```

```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
#Mean daily temps for each year - faceted by decade - and plotted by life-stage for Coho

#Coho rearing
decade_CO_r <- CO_r %>% group_by(day, year) %>% 
  summarize(mean_yr = mean(preds), sd_yr = sd(preds)) %>% mutate(decade=case_when(year< 1990 ~ 1980, year >= 1990 & year < 2000 ~ 1990, year >=2000 & year < 2010 ~ 2000, year>2009 ~ 2010))

ggplot(data=decade_CO_r) +
  geom_smooth(aes(x = day, y = mean_yr, color = as.factor(year)), show.legend = FALSE) + facet_wrap(~decade) + 
  ggtitle("Mean daily temperatures by year for Coho rearing habitat") 

ggsave("salmon_figs/Mean daily coho rearing thermal curve.jpeg", plot=last_plot())

#Coho spawning
decade_CO_s <- CO_s %>% group_by(day, year) %>% 
  summarize(mean_yr = mean(preds), sd_yr = sd(preds)) %>% mutate(decade=case_when(year< 1990 ~ 1980, year >= 1990 & year < 2000 ~ 1990, year >=2000 & year < 2010 ~ 2000, year>2009 ~ 2010))

ggplot(data=decade_CO_s) +
  geom_smooth(aes(x = day, y = mean_yr, color = as.factor(year)), show.legend = FALSE) + facet_wrap(~decade) + 
  ggtitle("Mean daily temperatures by year for Coho spawning habitat") 

ggsave("salmon_figs/Mean daily coho spawning thermal curve.jpeg", plot=last_plot())

```

#show quantity of habitat within degree celcius thermal niche
```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
hist_s <- K_s %>% group_by(rca_id, month, decade) %>% summarize(mth_mn=mean(preds)) %>% 
  mutate(bin=case_when(mth_mn>=1 & mth_mn<2 ~ 1, mth_mn>=2 & mth_mn<3 ~ 2, mth_mn>=3 & mth_mn<4 ~ 3,
                                     mth_mn>=4 & mth_mn<5 ~ 4, mth_mn>=5 & mth_mn<6 ~ 5, mth_mn>=6 & mth_mn<7 ~ 6,
                                     mth_mn>=7 & mth_mn<8 ~ 7, mth_mn>=8 & mth_mn<9 ~ 8, mth_mn>=9 & mth_mn<10 ~ 9,
                                     mth_mn>=10 & mth_mn<11 ~ 10, mth_mn>=11 & mth_mn<12 ~ 11, mth_mn>=12 & mth_mn<13 ~ 12,
                                     mth_mn>=13 & mth_mn<14 ~ 13, mth_mn>=14 & mth_mn<15 ~ 14))

#calculate total chinook spawning habitat = 	284418.7
total_s <- K_s %>%  filter(year==1980 & day==220) %>% summarize(total_hab=sum(reach_length))

len_s <- K_s %>% distinct(rca_id, reach_length) 

hist2_s <- left_join(hist_s, len_s, by="rca_id") %>% group_by(decade, month, bin) %>% 
    summarize(bin_total=sum(reach_length)) %>% 
        mutate(percent=(bin_total/284418.7)*100) 

#July
jul_s <- hist2_s %>% filter(month==7)

ggplot(data=jul_s) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean July Stream Temperatures for Chinook Spawning habitat")+
  scale_fill_discrete(name="Decade") + scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#aug
aug_s <- hist2_s %>% filter(month==8)

ggplot(data=aug_s) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean August Stream Temperatures for Chinook Spawning habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#sep
sep_s <- hist2_s %>% filter(month==9)

ggplot(data=sep_s) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean September Stream Temperatures for Chinook spawning habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))
```

#histograms of percent habitat for each degree celcius - Chinook Rearing habitat
```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
hist_r <- K_r %>% group_by(rca_id, month, decade) %>% summarize(mth_mn=mean(preds)) %>% 
  mutate(bin=case_when(mth_mn>=1 & mth_mn<2 ~ 1, mth_mn>=2 & mth_mn<3 ~ 2, mth_mn>=3 & mth_mn<4 ~ 3,
                                     mth_mn>=4 & mth_mn<5 ~ 4, mth_mn>=5 & mth_mn<6 ~ 5, mth_mn>=6 & mth_mn<7 ~ 6,
                                     mth_mn>=7 & mth_mn<8 ~ 7, mth_mn>=8 & mth_mn<9 ~ 8, mth_mn>=9 & mth_mn<10 ~ 9,
                                     mth_mn>=10 & mth_mn<11 ~ 10, mth_mn>=11 & mth_mn<12 ~ 11, mth_mn>=12 & mth_mn<13 ~ 12,
                                     mth_mn>=13 & mth_mn<14 ~ 13, mth_mn>=14 & mth_mn<15 ~ 14))

#calculate total chinook rearing habitat = 	176816.9
total_r <- K_r %>%  filter(year==1980 & day==220) %>% summarize(total_hab=sum(reach_length))

len_r <- K_r %>% distinct(rca_id, reach_length) 

hist2_r <- left_join(hist_r, len_r, by="rca_id") %>% group_by(decade, month, bin) %>% 
  summarize(bin_total=sum(reach_length)) %>% 
        mutate(percent=(bin_total/176816.9)*100)

#June
jun_r <- hist2_r %>% filter(month==6)

ggplot(data=jun_r) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean June Stream Temperatures for Chinook   Rearing habitat")+  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#July
jul_r <- hist2_r %>% filter(month==7)

ggplot(data=jul_r) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean July Stream Temperatures for Chinook Rearing habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#aug
aug_r <- hist2_r %>% filter(month==8)

ggplot(data=aug_r) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean August Stream Temperatures for Chinook Rearing habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

```


#show quantity of habitat within degree celcius thermal niche - coho
```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
hist_s2 <- CO_s %>% group_by(rca_id, month, decade) %>% summarize(mth_mn=mean(preds)) %>% 
  mutate(bin=case_when(mth_mn>=1 & mth_mn<2 ~ 1, mth_mn>=2 & mth_mn<3 ~ 2, mth_mn>=3 & mth_mn<4 ~ 3,
                                     mth_mn>=4 & mth_mn<5 ~ 4, mth_mn>=5 & mth_mn<6 ~ 5, mth_mn>=6 & mth_mn<7 ~ 6,
                                     mth_mn>=7 & mth_mn<8 ~ 7, mth_mn>=8 & mth_mn<9 ~ 8, mth_mn>=9 & mth_mn<10 ~ 9,
                                     mth_mn>=10 & mth_mn<11 ~ 10, mth_mn>=11 & mth_mn<12 ~ 11, mth_mn>=12 & mth_mn<13 ~ 12,
                                     mth_mn>=13 & mth_mn<14 ~ 13, mth_mn>=14 & mth_mn<15 ~ 14))

#calculate total coho spawning habitat = 	283157.9
total_s2 <- CO_s %>%  filter(year==1980 & day==220) %>% summarize(total_hab=sum(reach_length))

len_s2 <- CO_s %>% distinct(rca_id, reach_length) 

hist2_s2 <- left_join(hist_s2, len_s2, by="rca_id") %>% group_by(decade, month, bin) %>% 
    summarize(bin_total=sum(reach_length)) %>% 
        mutate(percent=(bin_total/283157.9)*100) 

#July
jul_s2 <- hist2_s2 %>% filter(month==7)

ggplot(data=jul_s2) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean July Stream Temperatures for Coho Spawning habitat")+
  scale_fill_discrete(name="Decade") + scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#aug
aug_s2 <- hist2_s2 %>% filter(month==8)

ggplot(data=aug_s2) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean August Stream Temperatures for Coho Spawning habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#sep
sep_s2 <- hist2_s2 %>% filter(month==9)

ggplot(data=sep_s2) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean September Stream Temperatures for Coho spawning habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))
```

#histograms of percent habitat for each degree celcius - Coho Rearing habitat
```{r, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.align="center", fig.width=6, fig.asp=1}
hist_r2 <- CO_r %>% group_by(rca_id, month, decade) %>% summarize(mth_mn=mean(preds)) %>% 
  mutate(bin=case_when(mth_mn>=1 & mth_mn<2 ~ 1, mth_mn>=2 & mth_mn<3 ~ 2, mth_mn>=3 & mth_mn<4 ~ 3,
                                     mth_mn>=4 & mth_mn<5 ~ 4, mth_mn>=5 & mth_mn<6 ~ 5, mth_mn>=6 & mth_mn<7 ~ 6,
                                     mth_mn>=7 & mth_mn<8 ~ 7, mth_mn>=8 & mth_mn<9 ~ 8, mth_mn>=9 & mth_mn<10 ~ 9,
                                     mth_mn>=10 & mth_mn<11 ~ 10, mth_mn>=11 & mth_mn<12 ~ 11, mth_mn>=12 & mth_mn<13 ~ 12,
                                     mth_mn>=13 & mth_mn<14 ~ 13, mth_mn>=14 & mth_mn<15 ~ 14))

#calculate total coho rearing habitat = 340586.1	
total_r2 <- CO_r %>%  filter(year==1980 & day==220) %>% summarize(total_hab=sum(reach_length))

len_r2 <- CO_r %>% distinct(rca_id, reach_length) 

hist2_r2 <- left_join(hist_r2, len_r2, by="rca_id") %>% group_by(decade, month, bin) %>% 
  summarize(bin_total=sum(reach_length)) %>% 
        mutate(percent=(bin_total/340586.1)*100)

#June
jun_r2 <- hist2_r2 %>% filter(month==6)

ggplot(data=jun_r2) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean June Stream Temperatures for Coho Rearing habitat")+  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#July
jul_r2 <- hist2_r2 %>% filter(month==7)

ggplot(data=jul_r2) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean July Stream Temperatures for Coho Rearing habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

#aug
aug_r2 <- hist2_r2 %>% filter(month==8)

ggplot(data=aug_r2) + geom_bar(aes(x=bin, y=percent, fill=as.factor(decade)), stat = "identity")+
  facet_wrap(~decade) + 
  labs(x="Temperature", y="Percent total habitat", title="Mean August Stream Temperatures for Coho Rearing habitat")+
  scale_fill_discrete(name="Decade")+ scale_x_continuous(breaks = c(2,4,6,8,10,12,14))

```


```{r}
#clear global environment
remove(list = ls())
```

